# Generated by Django 5.1.4 on 2025-01-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_rename_role_role_name_remove_role_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
