"""organization migration

Revision ID: d13e3e38c5a7
Revises: 0c6873a973ae
Create Date: 2025-02-17 13:44:31.662781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13e3e38c5a7'
down_revision: Union[str, None] = '0c6873a973ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'super_admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('fk_organizations_super_admin_id', 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'users', ['super_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key('fk_organizations_super_admin_id', 'organizations', 'users', ['super_admin_id'], ['id'], ondelete='CASCADE')
    op.alter_column('organizations', 'super_admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
