"""mig

Revision ID: ee486efb3abc
Revises: 45b69a53d11c
Create Date: 2025-02-07 16:09:54.674698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee486efb3abc'
down_revision: Union[str, None] = '45b69a53d11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Admin', 'Manager', 'Member', name='userrole'),
               existing_nullable=False)
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('Admin', 'Manager', 'Member', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
