"""organization migration

Revision ID: f0b4e3bc2590
Revises: ba47873c17a2
Create Date: 2025-02-17 11:49:19.720151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b4e3bc2590'
down_revision: Union[str, None] = 'ba47873c17a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'organizations', ['organization_id'], ['id'])
    op.add_column('teams', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'organization_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'organization_id')
    # ### end Alembic commands ###
